config/routes.rb
Rails.application.routes.draw do

  resources :categories, only: [:show, :index]
  
  resources :tickets, only: [:index, :show, :create, :edit]
  

  resources :comments, only: [:create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :tickets
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tickets
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

   def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !!current_user
    end

  def original_author?(user)
    self.user == user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   def show
  	@category = Category.find(params[:id])
  	@categories = Category.all
  	@tickets = @category.tickets
  	@ticket = Ticket.new
  end

  def index
  	@categories = Category.all
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def create
  	current_user
  	@ticket = Ticket.find(params[:ticket_id])
  	@comment = Comment.new(comment_params)
  	@comment.user = current_user
  	@ticket.comments << @comment
  	# @comment = @ticket.comments.new(comment_params)
  	if @comment.save
  	# partial later
  		redirect_to :back
  	else
  		hi what are you doing
  	end
  end

  def show
  	@ticket = Ticket.find(params[:ticket_id])
  	#partial later
  	render 'ticket/show'
  end

  private
  	def comment_params
  		params.require(:comment).permit(:user, :body)
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user && @user.authenticate(params[:password])
  		session[:user_id] = @user.id
  		redirect_to categories_path
  	else
  		flash[:alert] = "Something went wrong. make sure you filled in all fields correctly."
  		redirect_to new_session_path
  	end
  end

  def destroy
  	session.clear
  	session[:user_id] = nil
  	redirect_to categories_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  	@ticket = Ticket.all
  end

  def show
  	@ticket = Ticket.find(params[:id])

  	@comment = Comment.new
  	@comments = @ticket.comments.order(created_at: :asc)
  


  end 

  def create
  	@category = Category.find(params[:category_id])
  	@user = current_user
  	@ticket = Ticket.create(ticket_params)
  end

  def edit
  end

  private
  def ticket_params
    params.require(:ticket).permit(:issue, :description, :level, :housing_project, :building, :other_details, :image, :status, :user, :category).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	    @user = User.new(user_params)
    if @user.save
      redirect_to categories_path
    else
      alert.now[:bad_registration] = "Bad registration"
    end
  end

  private 

  def user_params
  	params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
	<% @categories.each do |category| %>
		<li>
		<%=link_to category.name, category%>
		</li>
	<%end%>
</ul>

app/views/categories/show.html.erb
<h1><%=@category.name%></h1>
<ul>
	<% @category.tickets.each do |ticket|%>
		<li>
		<%=link_to ticket.issue, ticket%> | <%=ticket.housing_project%>, <%=ticket.building%>
		</li>
	<%end%>
</ul>

<%if logged_in?%>
	<%=form_for @ticket do |f|%>
	<%= hidden_field_tag('category_id', @category.id) %>

	<p>File a Ticket</p>
	<%=f.label :issue%>
	<%= f.text_field :issue%><p>
	<%=f.label :description%>
	<%= f.text_area :description%><p>
	<%=f.label :level%>
	<%= f.text_area :level%><p>
	<%=f.label :housing_project%>
	<%= f.text_area :housing_project%><p>
	<%=f.label :building%>
	<%= f.text_area :building%><p>
	<%=f.label :other_details%>
	<%= f.text_area :other_details%><p>
	<%=f.label :optional_image%>
	<%= f.text_area :image%><p>
	<%= f.select(:category, @categories.collect{|category| category.name})%><p>
	<%= f.submit %>
	<%end%>
<%end%>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NYCHA Ticket Filing System</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 id='heading'>NYCHA Ticket Filing System</h1>

<%if !logged_in?%>
  <%=link_to 'login', new_session_path%> | <%=link_to 'register', new_user_path%></li>
  <%else%>
    <li><%=link_to 'logout', session_path(User.find(session[:user_id])), method: :delete%></li>
  <%end%> | <%=link_to 'home', categories_path%>

<%= yield %>

</body>
</html>

app/views/tickets/create.html.erb
<h1>Tickets#create</h1>
<p>Find me in app/views/tickets/create.html.erb</p>

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<p>Find me in app/views/tickets/edit.html.erb</p>

app/views/tickets/index.html.erb
<h1>Tickets#index</h1>
<p>Find me in app/views/tickets/index.html.erb</p>

app/views/tickets/show.html.erb
<h2>Ticket #<%=@ticket.id%>: <%=@ticket.issue%></h2>

<h3><%=@ticket.housing_project%>, <%=@ticket.building%>, <%=@ticket.other_details%></h3>

<h3>Priority Level: <%=@ticket.level%></h3>
<h3>Status:
	<%if @ticket.status%>
		Closed
	<%else%>
		Open
	<%end%>
</h3>


</h3>


<h3>Filed at <%=@ticket.created_at%> by <%=@ticket.user.email%></h3>

<h3>

<h4>Issue Description</h4>
----
	<p>
		<%=@ticket.description%>
	</p>
----

	<ul>
		<%@comments.each do |comment|%>
			<li><h5><%=comment.user.email%></h5></li>
				<p><%=comment.body%><p>

				-----

		<%end%>
		</ul>



<%if logged_in?%>
	<%=form_for @comment do |f|%>
	<%= hidden_field_tag('ticket_id', @ticket.id) %>

	<p>Add a Comment or an Update</p>
	<%= f.text_area :body%>
	<%= f.submit %>
	<%end%>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h4>Register</h4>
<%= form_for @user  do |f| %>
  <%=f.label "Email"%>
  <%=f.text_field :email %>
  <%=f.label "Password"%>
  <%=f.password_field :password %>
  <%= f.submit "Join"%>
  <% end %>